import { Router } from 'express';
import actionRouter from './sendEmailRouter';
import majorRouter from './majorRouter';
import authRouter from './userRouter';
import projectSessionRouter from './projectSessionRouter';
import academicYearRouter from './academicYearRouter';
import studentRouter from './studentRouter';
import roundSessionRouter from './roundSessionRouter';
import registerProjectRouter from './registerProjectRouter';
import approveProjectRouter from './approveProjectRouter';
import fileRouter from './fileRouter';
const router = Router();

router.use('/action', actionRouter);
router.use('/major', majorRouter);
router.use('/auth', authRouter);
router.use('/projectSession', projectSessionRouter);
router.use('/academicYear', academicYearRouter);
router.use('/student', studentRouter);
router.use('/round', roundSessionRouter);
router.use('/register-project', registerProjectRouter);
router.use('/approve-project', approveProjectRouter);
router.use('/file', fileRouter);
export default router;
